services:

  db:
    image: postgres
    container_name: publications-db
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - publications-db-data:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=publications
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  db_admin:
    image: dpage/pgadmin4
    container_name: publications-db-admin
    restart: always
    secrets:
      - db-admin-password
    environment:
      - PGADMIN_DEFAULT_EMAIL=johnnyb1694@gmail.com
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/db-admin-password
    ports:
      - 8888:80
    volumes:
      - publications-db-admin-data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

volumes:
  publications-db-data:
  publications-db-admin-data:

secrets:
  db-password:
    file: env/DB_PWD.txt
  db-admin-password:
    file: env/DB_ADMIN_PWD.txt
