# ---- Metadata ----

name: 'data_transformer'
version: '1.0.0'

# ---- Connection Profiles ----

profile: 'data_transformer'

# ---- Paths ----

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# ---- Cleanup ----

clean-targets:       
  - "target"
  - "dbt_packages"


# ---- Model Configuration ----

# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the staging/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  data_transformer:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
